name = "Adventures Beyond"
author = "Shammrockss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6832374822801bd3b670bfa599b11ea87de658c38182261f16d091cae63a5eb"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.X", "1.20.x"]
