name = "Adventures Beyond"
author = "Shammrockss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0eda6f539b117d013818a45bc0307b913620104b522358832d81cb3b9446ca14"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.X", "1.20.x"]
