name = "Adventures Beyond"
author = "Shammrockss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9070bbaec67d3a13778c42bd9baf89ed3eb7c7e6962f2210fdc6e5b40fdbb83"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.X", "1.20.x"]
