name = "Adventures Beyond"
author = "Shammrockss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac83447e74ca1028af4826adf2b242f45706e3797cc50c36545a787ad49ca5a0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.X", "1.20.x"]
