name = "Adventures Beyond"
author = "Shammrockss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a10f35446a5492ac7b4a5a1956c7533b5e0710ea4ebaf82d8af4cd7649cb9d27"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.X", "1.20.x"]
